/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import Model.Conexion;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JOptionPane;

/**
 *
 * @author alejandrovelasco
 */
public class AltaDatosProfecionalesScreen extends javax.swing.JPanel {

    /**
     * Creates new form AltaDatosProfecionales
     */
    public AltaDatosProfecionalesScreen() {
        initComponents();
        
        btnGuardar.setIcon(setIcon("/imagenes/salvar.png", btnGuardar));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtExperiencia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTrabajo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JTextField();
        controls = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(102, 255, 153));
        head.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Alta de Datos Profecionales");
        head.add(jLabel1);

        add(head, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(204, 255, 204));
        body.setLayout(new javax.swing.BoxLayout(body, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 44));
        jPanel1.setPreferredSize(new java.awt.Dimension(490, 44));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel2.setText("Experiencia laboral");
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 17));
        jPanel1.add(jLabel2);

        txtExperiencia.setToolTipText("");
        txtExperiencia.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel1.add(txtExperiencia);

        body.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 44));
        jPanel2.setPreferredSize(new java.awt.Dimension(490, 44));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel3.setText("Trabajo anterior");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 17));
        jPanel2.add(jLabel3);

        txtTrabajo.setToolTipText("");
        txtTrabajo.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel2.add(txtTrabajo);

        body.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 44));
        jPanel3.setPreferredSize(new java.awt.Dimension(490, 44));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel4.setText("Cedula Profecional");
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 17));
        jPanel3.add(jLabel4);

        txtCedula.setToolTipText("");
        txtCedula.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel3.add(txtCedula);

        body.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 44));
        jPanel4.setPreferredSize(new java.awt.Dimension(490, 44));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel5.setText("Especialidad");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 17));
        jPanel4.add(jLabel5);

        txtEspecialidad.setToolTipText("");
        txtEspecialidad.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel4.add(txtEspecialidad);

        body.add(jPanel4);

        controls.setBackground(new java.awt.Color(204, 255, 204));
        controls.setMaximumSize(new java.awt.Dimension(32767, 44));
        controls.setPreferredSize(new java.awt.Dimension(490, 44));
        controls.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        controls.add(btnGuardar);

        body.add(controls);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         try {
            //DB conexion
            Conexion cc = new Conexion();
            Connection cn = cc.conectar();
            PreparedStatement ps = cn.prepareStatement("INSERT INTO datos_profecionales VALUES(?,?,?,?);");

            if (txtExperiencia.getText().isEmpty()
                    || txtTrabajo.getText().isEmpty()
                    || txtCedula.getText().isEmpty()
                    || txtEspecialidad.getText().isEmpty()){

                JOptionPane.showMessageDialog(null, "Tienes valores invalidos o nulos",
                        "Hey!", JOptionPane.ERROR_MESSAGE);
            } else {

                ps.setString(1, txtExperiencia.getText());
                ps.setString(2, txtTrabajo.getText());
                ps.setString(3, txtCedula.getText());
                ps.setString(4, txtEspecialidad.getText());
                
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Registro Exitoso",
                        "Hey!", JOptionPane.INFORMATION_MESSAGE);

                txtEspecialidad.setText("");
                txtTrabajo.setText("");
                txtCedula.setText("");
                txtExperiencia.setText("");
               
            }

        } catch (SQLException ex) {
            Logger.getLogger(AltaDocenteScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    public Icon setIcon(String url, JButton menu){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = 24;
        int alto = 24;
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel controls;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtExperiencia;
    private javax.swing.JTextField txtTrabajo;
    // End of variables declaration//GEN-END:variables
}
