package Screens;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alejandrovelasco
 */
public class AltaDocenteScreen extends javax.swing.JPanel {

    /**
     * Creates new form AltaDocenteScreen
     */
    public AltaDocenteScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        text1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        text2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        text3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        text4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        text5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        text6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        text7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        controls = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(153, 153, 255));
        head.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Alta de docentes");
        head.add(jLabel1);

        add(head, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(204, 204, 255));
        body.setLayout(new javax.swing.BoxLayout(body, javax.swing.BoxLayout.PAGE_AXIS));

        text1.setBackground(new java.awt.Color(204, 204, 255));
        text1.setMaximumSize(new java.awt.Dimension(32767, 33));
        text1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel2.setText("Id Docente");
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 17));
        text1.add(jLabel2);

        jTextField1.setMinimumSize(new java.awt.Dimension(200, 23));
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 23));
        text1.add(jTextField1);

        body.add(text1);

        text2.setBackground(new java.awt.Color(204, 204, 255));
        text2.setMaximumSize(new java.awt.Dimension(32767, 33));
        text2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel3.setText("Nombre");
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 17));
        text2.add(jLabel3);

        jTextField2.setMinimumSize(new java.awt.Dimension(200, 23));
        jTextField2.setPreferredSize(new java.awt.Dimension(200, 23));
        text2.add(jTextField2);

        body.add(text2);

        text3.setBackground(new java.awt.Color(204, 204, 255));
        text3.setMaximumSize(new java.awt.Dimension(32767, 33));
        text3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel4.setText("Apellidos");
        jLabel4.setPreferredSize(new java.awt.Dimension(70, 17));
        text3.add(jLabel4);

        jTextField3.setMinimumSize(new java.awt.Dimension(200, 23));
        jTextField3.setPreferredSize(new java.awt.Dimension(200, 23));
        text3.add(jTextField3);

        body.add(text3);

        text4.setBackground(new java.awt.Color(204, 204, 255));
        text4.setMaximumSize(new java.awt.Dimension(32767, 33));
        text4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel5.setText("RFC");
        jLabel5.setPreferredSize(new java.awt.Dimension(70, 17));
        text4.add(jLabel5);

        jTextField4.setMinimumSize(new java.awt.Dimension(200, 23));
        jTextField4.setPreferredSize(new java.awt.Dimension(200, 23));
        text4.add(jTextField4);

        body.add(text4);

        text5.setBackground(new java.awt.Color(204, 204, 255));
        text5.setMaximumSize(new java.awt.Dimension(32767, 33));
        text5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel6.setText("Direccion");
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 17));
        text5.add(jLabel6);

        jTextField5.setMinimumSize(new java.awt.Dimension(200, 23));
        jTextField5.setPreferredSize(new java.awt.Dimension(200, 23));
        text5.add(jTextField5);

        body.add(text5);

        text6.setBackground(new java.awt.Color(204, 204, 255));
        text6.setMaximumSize(new java.awt.Dimension(32767, 33));
        text6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel7.setText("Estado civil");
        jLabel7.setPreferredSize(new java.awt.Dimension(70, 17));
        text6.add(jLabel7);

        jTextField6.setMinimumSize(new java.awt.Dimension(200, 23));
        jTextField6.setPreferredSize(new java.awt.Dimension(200, 23));
        text6.add(jTextField6);

        body.add(text6);

        text7.setBackground(new java.awt.Color(204, 204, 255));
        text7.setMaximumSize(new java.awt.Dimension(32767, 33));
        text7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel8.setText("Telefono");
        jLabel8.setPreferredSize(new java.awt.Dimension(70, 17));
        text7.add(jLabel8);

        jTextField7.setMinimumSize(new java.awt.Dimension(200, 23));
        jTextField7.setPreferredSize(new java.awt.Dimension(200, 23));
        text7.add(jTextField7);

        body.add(text7);

        controls.setBackground(new java.awt.Color(204, 204, 255));
        controls.setMaximumSize(new java.awt.Dimension(32767, 33));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        controls.setLayout(flowLayout1);

        jButton1.setText("Guardar");
        controls.add(jButton1);

        body.add(controls);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel controls;
    private javax.swing.JPanel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel text1;
    private javax.swing.JPanel text2;
    private javax.swing.JPanel text3;
    private javax.swing.JPanel text4;
    private javax.swing.JPanel text5;
    private javax.swing.JPanel text6;
    private javax.swing.JPanel text7;
    // End of variables declaration//GEN-END:variables
}
