/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

/**
 *
 * @author alejandrovelasco
 */
public class AltaDatosProfecionalesScreen extends javax.swing.JPanel {

    /**
     * Creates new form AltaDatosProfecionales
     */
    public AltaDatosProfecionalesScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        controls = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(102, 255, 153));
        head.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Alta de Datos Profecionales");
        head.add(jLabel1);

        add(head, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(204, 255, 204));
        body.setLayout(new javax.swing.BoxLayout(body, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 44));
        jPanel1.setPreferredSize(new java.awt.Dimension(490, 44));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel2.setText("Experiencia laboral");
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 17));
        jPanel1.add(jLabel2);

        jTextField1.setToolTipText("");
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel1.add(jTextField1);

        body.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 44));
        jPanel2.setPreferredSize(new java.awt.Dimension(490, 44));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel3.setText("Trabajo anterior");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 17));
        jPanel2.add(jLabel3);

        jTextField2.setToolTipText("");
        jTextField2.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel2.add(jTextField2);

        body.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 44));
        jPanel3.setPreferredSize(new java.awt.Dimension(490, 44));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel4.setText("Cedula Profecional");
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 17));
        jPanel3.add(jLabel4);

        jTextField3.setToolTipText("");
        jTextField3.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel3.add(jTextField3);

        body.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 44));
        jPanel4.setPreferredSize(new java.awt.Dimension(490, 44));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel5.setText("Especialidad");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 17));
        jPanel4.add(jLabel5);

        jTextField4.setToolTipText("");
        jTextField4.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel4.add(jTextField4);

        body.add(jPanel4);

        controls.setBackground(new java.awt.Color(204, 255, 204));
        controls.setMaximumSize(new java.awt.Dimension(32767, 44));
        controls.setPreferredSize(new java.awt.Dimension(490, 44));
        controls.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jButton1.setText("Guardar");
        controls.add(jButton1);

        body.add(controls);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel controls;
    private javax.swing.JPanel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
