package Screens;

import Model.Conexion;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import org.sqlite.SQLiteException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alejandrovelasco
 */
public class AltaDocenteScreen extends javax.swing.JPanel {

    /**
     * Creates new form AltaDocenteScreen
     */
    public AltaDocenteScreen() {
        initComponents();
        try {
            btnGuardar.setIcon(setIcon("/imagenes/salvar.png", btnGuardar));
            btnDelete.setIcon(setIcon("/imagenes/delete.png", btnDelete));
        } catch (Exception e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        text1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        text2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        text3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        text4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        text5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        text6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        text7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        text8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtGradoAcad = new javax.swing.JTextField();
        controls = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        controls2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDeleteid = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(255, 255, 255));
        head.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        head.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Alta de docentes");
        head.add(jLabel1);

        add(head, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new javax.swing.BoxLayout(body, javax.swing.BoxLayout.PAGE_AXIS));

        text1.setBackground(new java.awt.Color(255, 255, 255));
        text1.setMaximumSize(new java.awt.Dimension(32767, 40));
        text1.setMinimumSize(new java.awt.Dimension(32767, 30));
        text1.setPreferredSize(new java.awt.Dimension(300, 45));
        text1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel2.setText("Id Docente");
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 17));
        text1.add(jLabel2);

        txtID.setMinimumSize(new java.awt.Dimension(200, 23));
        txtID.setPreferredSize(new java.awt.Dimension(200, 30));
        text1.add(txtID);

        body.add(text1);

        text2.setBackground(new java.awt.Color(255, 255, 255));
        text2.setMaximumSize(new java.awt.Dimension(32767, 40));
        text2.setMinimumSize(new java.awt.Dimension(32767, 44));
        text2.setPreferredSize(new java.awt.Dimension(300, 43));
        text2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel3.setText("Nombre");
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 17));
        text2.add(jLabel3);

        txtNombre.setMinimumSize(new java.awt.Dimension(200, 23));
        txtNombre.setPreferredSize(new java.awt.Dimension(200, 30));
        text2.add(txtNombre);

        text3.setBackground(new java.awt.Color(255, 255, 255));
        text3.setMaximumSize(new java.awt.Dimension(32767, 40));
        text3.setMinimumSize(new java.awt.Dimension(32767, 44));
        text3.setPreferredSize(new java.awt.Dimension(300, 43));
        text3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel4.setText("Apellidos");
        jLabel4.setPreferredSize(new java.awt.Dimension(70, 17));
        text3.add(jLabel4);

        txtApellidos.setMinimumSize(new java.awt.Dimension(200, 23));
        txtApellidos.setPreferredSize(new java.awt.Dimension(200, 30));
        text3.add(txtApellidos);

        text2.add(text3);

        body.add(text2);

        text4.setBackground(new java.awt.Color(255, 255, 255));
        text4.setMaximumSize(new java.awt.Dimension(32767, 40));
        text4.setMinimumSize(new java.awt.Dimension(32767, 44));
        text4.setPreferredSize(new java.awt.Dimension(300, 43));
        text4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel5.setText("RFC");
        jLabel5.setPreferredSize(new java.awt.Dimension(70, 17));
        text4.add(jLabel5);

        txtRfc.setMinimumSize(new java.awt.Dimension(200, 23));
        txtRfc.setPreferredSize(new java.awt.Dimension(200, 30));
        text4.add(txtRfc);

        text5.setBackground(new java.awt.Color(255, 255, 255));
        text5.setMaximumSize(new java.awt.Dimension(32767, 40));
        text5.setMinimumSize(new java.awt.Dimension(32767, 44));
        text5.setPreferredSize(new java.awt.Dimension(300, 43));
        text5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel6.setText("Direccion");
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 17));
        text5.add(jLabel6);

        txtDireccion.setMinimumSize(new java.awt.Dimension(200, 23));
        txtDireccion.setPreferredSize(new java.awt.Dimension(200, 30));
        text5.add(txtDireccion);

        text4.add(text5);

        body.add(text4);

        text6.setBackground(new java.awt.Color(255, 255, 255));
        text6.setMaximumSize(new java.awt.Dimension(32767, 40));
        text6.setMinimumSize(new java.awt.Dimension(32767, 44));
        text6.setPreferredSize(new java.awt.Dimension(300, 43));
        text6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel7.setText("Estado civil");
        jLabel7.setPreferredSize(new java.awt.Dimension(70, 17));
        text6.add(jLabel7);

        txtEstadoCivil.setMinimumSize(new java.awt.Dimension(200, 23));
        txtEstadoCivil.setPreferredSize(new java.awt.Dimension(200, 30));
        text6.add(txtEstadoCivil);

        text7.setBackground(new java.awt.Color(255, 255, 255));
        text7.setMaximumSize(new java.awt.Dimension(32767, 40));
        text7.setMinimumSize(new java.awt.Dimension(32767, 44));
        text7.setPreferredSize(new java.awt.Dimension(300, 43));
        text7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel8.setText("Telefono");
        jLabel8.setPreferredSize(new java.awt.Dimension(70, 17));
        text7.add(jLabel8);

        txtTelefono.setMinimumSize(new java.awt.Dimension(200, 23));
        txtTelefono.setPreferredSize(new java.awt.Dimension(200, 30));
        text7.add(txtTelefono);

        text6.add(text7);

        body.add(text6);

        text8.setBackground(new java.awt.Color(255, 255, 255));
        text8.setMaximumSize(new java.awt.Dimension(32767, 40));
        text8.setMinimumSize(new java.awt.Dimension(32767, 30));
        text8.setPreferredSize(new java.awt.Dimension(300, 45));
        text8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel9.setText("Ultimo grado de estudios");
        jLabel9.setAutoscrolls(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 17));
        text8.add(jLabel9);

        txtGradoAcad.setMinimumSize(new java.awt.Dimension(200, 23));
        txtGradoAcad.setPreferredSize(new java.awt.Dimension(200, 30));
        text8.add(txtGradoAcad);

        body.add(text8);

        controls.setBackground(new java.awt.Color(255, 255, 255));
        controls.setMaximumSize(new java.awt.Dimension(32767, 50));
        controls.setMinimumSize(new java.awt.Dimension(97, 50));
        controls.setPreferredSize(new java.awt.Dimension(97, 50));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        controls.setLayout(flowLayout1);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        controls.add(btnGuardar);

        body.add(controls);

        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        body.add(jSeparator1);

        controls2.setBackground(new java.awt.Color(255, 255, 255));
        controls2.setMaximumSize(new java.awt.Dimension(32767, 50));
        controls2.setMinimumSize(new java.awt.Dimension(97, 50));
        controls2.setPreferredSize(new java.awt.Dimension(97, 50));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10);
        flowLayout3.setAlignOnBaseline(true);
        controls2.setLayout(flowLayout3);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Eliminar un registro: ");
        controls2.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel11.setText("Id  Registro");
        controls2.add(jLabel11);

        txtDeleteid.setPreferredSize(new java.awt.Dimension(90, 30));
        txtDeleteid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteidActionPerformed(evt);
            }
        });
        controls2.add(txtDeleteid);

        body.add(controls2);

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        body.add(btnDelete);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Conexion cc = new Conexion();
        if (txtID.getText().isEmpty()
                || txtNombre.getText().isEmpty()
                || txtApellidos.getText().isEmpty()
                || txtRfc.getText().isEmpty()
                || txtEstadoCivil.getText().isEmpty()
                || txtDireccion.getText().isEmpty()
                || txtTelefono.getText().isEmpty()
                || txtGradoAcad.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Tienes valores invalidos o nulos",
                    "Hey!", JOptionPane.ERROR_MESSAGE);
        }

        try {
            String id, consult, stateRegister;
            
            Connection cn = cc.conectar();
            id = txtID.getText();
            
                PreparedStatement ps = cn.prepareStatement("INSERT INTO docente VALUES(?,?,?,?,?,?,?,?,?);");
                ps.setString(1, txtID.getText());
                ps.setString(2, txtNombre.getText());
                ps.setString(3, txtApellidos.getText());
                ps.setString(4, txtRfc.getText());
                ps.setString(5, txtEstadoCivil.getText());
                ps.setString(6, txtDireccion.getText());
                ps.setString(7, txtTelefono.getText());
                ps.setString(8, txtGradoAcad.getText());
                ps.setString(9, "Activo");
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Registro Exitoso",
                        "Hey!", JOptionPane.INFORMATION_MESSAGE);

                txtID.setText("");
                txtNombre.setText("");
                txtApellidos.setText("");
                txtRfc.setText("");
                txtEstadoCivil.setText("");
                txtDireccion.setText("");
                txtTelefono.setText("");
                txtGradoAcad.setText("");
                
                ps.close();
                cn.close();

        } catch (SQLException ex) {
            Logger.getLogger(AltaDocenteScreen.class.getName()).log(Level.SEVERE, null, ex);
            if (ex.getMessage().contains("SQLITE_CONSTRAINT_PRIMARYKEY")) {
                JOptionPane.showMessageDialog(null, "El id ya esta en uso o es invalido digite uno diferente",
                        "Hey!", JOptionPane.ERROR_MESSAGE);
                System.out.println("Error - Unique Key Violation!!");
            } else {
                System.out.println("Other Error: " + ex.getMessage());
            }
        } catch (Exception ex) {
            Logger.getLogger(AltaDocenteScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtDeleteidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteidActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        try {

            String id, sentence, consult, stateRegister;
            Conexion cc = new Conexion();
            Connection cn = cc.conectar();

            Statement st = cn.createStatement();
           
            id = txtDeleteid.getText();

            consult = "SELECT * FROM docente WHERE id=" + id;
            ResultSet data = st.executeQuery(consult);
            stateRegister = data.getString("estado");

            //System.out.println(stateRegister);
            if (stateRegister.equals("inactivo")) {
                JOptionPane.showMessageDialog(null, "El registro ya esta inactivo",
                        "Hey!", JOptionPane.WARNING_MESSAGE);
                txtDeleteid.setText("");
                st.close();
            } else {
                
                txtDeleteid.setText("");
                JOptionPane.showMessageDialog(null, "Se ha desactivado el registro",
                        "Hey!", JOptionPane.WARNING_MESSAGE);
                st.executeQuery("UPDATE docente SET estado = 'inactivo' WHERE id="+id);
                
                st.close();
            }

        } catch (Exception e) {
              System.out.println(e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    public Icon setIcon(String url, JButton menu) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = 24;
        int alto = 24;

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel controls;
    private javax.swing.JPanel controls2;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel text1;
    private javax.swing.JPanel text2;
    private javax.swing.JPanel text3;
    private javax.swing.JPanel text4;
    private javax.swing.JPanel text5;
    private javax.swing.JPanel text6;
    private javax.swing.JPanel text7;
    private javax.swing.JPanel text8;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDeleteid;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtGradoAcad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
