/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import Model.Conexion;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import org.sqlite.SQLiteException;

/**
 *
 * @author alejandrovelasco
 */
public class ConsultaPerfilScreen extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaPerfilScreen
     */
    public ConsultaPerfilScreen() {
        initComponents();
        try {
            btnBuscar.setIcon(setIcon("/imagenes/search1.png", btnBuscar));
            btnDelete.setIcon(setIcon("/imagenes/delete.png", btnDelete));
        } catch (Exception e) {
            System.err.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        searchPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        controlsPane = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        controlsPane1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbGrado = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbCedula = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lbExperiencia = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lbEspecialidad = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Consulta de Perfil");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 204, 255));
        body.setLayout(new javax.swing.BoxLayout(body, javax.swing.BoxLayout.PAGE_AXIS));

        searchPane.setBackground(new java.awt.Color(255, 204, 255));
        searchPane.setMaximumSize(new java.awt.Dimension(32767, 35));

        jLabel2.setText("Buscar ID");
        searchPane.add(jLabel2);

        txtSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        searchPane.add(txtSearch);

        body.add(searchPane);

        controlsPane.setBackground(new java.awt.Color(255, 204, 255));
        controlsPane.setMaximumSize(new java.awt.Dimension(32767, 35));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        controlsPane.add(btnBuscar);

        btnDelete.setText("Borrar busqueda");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        controlsPane.add(btnDelete);

        body.add(controlsPane);

        controlsPane1.setBackground(new java.awt.Color(255, 204, 255));
        controlsPane1.setMaximumSize(new java.awt.Dimension(32767, 35));
        body.add(controlsPane1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        panel2.setLayout(new javax.swing.BoxLayout(panel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBackground(new java.awt.Color(219, 174, 219));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setText("Ultimo Grado de estudios");
        jPanel4.add(jLabel8);
        jPanel4.add(lbGrado);

        panel2.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(219, 174, 219));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel10.setText("Cedula Profecional");
        jPanel6.add(jLabel10);
        jPanel6.add(lbCedula);

        panel2.add(jPanel6);

        jPanel9.setBackground(new java.awt.Color(219, 174, 219));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel16.setText("Experiencia Laboral");
        jPanel9.add(jLabel16);
        jPanel9.add(lbExperiencia);

        panel2.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(219, 174, 219));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel18.setText("Especialidad");
        jPanel10.add(jLabel18);
        jPanel10.add(lbEspecialidad);

        panel2.add(jPanel10);

        jPanel2.add(panel2, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(219, 174, 219));
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel22.setText("id");
        jPanel12.add(jLabel22);
        jPanel12.add(lbId);

        jPanel11.setBackground(new java.awt.Color(219, 174, 219));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jPanel3.setBackground(new java.awt.Color(219, 174, 219));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel3.add(jLabel4);
        jPanel3.add(lbNombre);

        jPanel11.add(jPanel3);

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel20.setText("Apellidos");
        jPanel11.add(jLabel20);
        jPanel11.add(lbApellidos);

        jPanel12.add(jPanel11);

        jPanel2.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        body.add(jPanel2);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        if (txtSearch.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo vacio", "Hey!!", JOptionPane.WARNING_MESSAGE);
            } 
        try {
            //DB conexion
            String id, sentence, consult,stateRegister;
            Conexion cc = new Conexion();
            Connection cn = cc.conectar();
            
            id = txtSearch.getText();
            
            Statement nst = cn.createStatement();
            consult = "SELECT * FROM docente WHERE id=" + id;
            ResultSet data = nst.executeQuery(consult);
            stateRegister = data.getString("estado");
            
            if(stateRegister.equals("inactivo")){
                JOptionPane.showMessageDialog(null, "El registro ya esta inactivo",
                        "Hey!", JOptionPane.WARNING_MESSAGE);
               
            }else{
                 
                 Statement st = cn.createStatement();
       
                sentence = "SELECT * FROM  docente INNER JOIN datos_profecionales ON docente.id = datos_profecionales.id_docente WHERE docente.id ==" + id;
                ResultSet datos = st.executeQuery(sentence);

                //Labes
                lbId.setText(datos.getString("id"));
                lbNombre.setText(datos.getString("nombre"));
                lbApellidos.setText(datos.getString("apellidos"));
                lbGrado.setText(datos.getString("ultimoGrado"));
                lbCedula.setText(datos.getString("cedula"));
                lbExperiencia.setText(datos.getString("expediente_laboral"));
                lbEspecialidad.setText(datos.getString("especialidad"));
            }

            
        } catch (SQLiteException e) {
            System.out.println(e);
            //Logger.getLogger(AltaDocenteScreen.class.getName()).log(Level.SEVERE, null, e);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Registro No encontrado o los datos no han sido completados", "Hey!!", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
            //Logger.getLogger(ConsultaPerfilScreen.class.getName()).log(Level.SEVERE, null, ex);

        } catch (Exception ex) {
            Logger.getLogger(ConsultaPerfilScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        txtSearch.setText("");
        lbId.setText("");
        lbNombre.setText("");
        lbApellidos.setText("");
        lbGrado.setText("");
        lbCedula.setText("");
        lbExperiencia.setText("");
        lbEspecialidad.setText("");

    }//GEN-LAST:event_btnDeleteActionPerformed

    public Icon setIcon(String url, JButton menu) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = 24;
        int alto = 24;

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel controlsPane;
    private javax.swing.JPanel controlsPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbEspecialidad;
    private javax.swing.JLabel lbExperiencia;
    private javax.swing.JLabel lbGrado;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel searchPane;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
