/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

/**
 *
 * @author alejandrovelasco
 */
public class ConsultaDocenteScreen extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaDocente
     */
    public ConsultaDocenteScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        searchPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        controlsPane = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(255, 255, 102));
        head.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Consulta de Docente");
        head.add(jLabel1);

        add(head, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 204));
        body.setLayout(new javax.swing.BoxLayout(body, javax.swing.BoxLayout.PAGE_AXIS));

        searchPane.setBackground(new java.awt.Color(255, 255, 204));
        searchPane.setMaximumSize(new java.awt.Dimension(32767, 44));
        searchPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel2.setText("Numero de Empleado");
        searchPane.add(jLabel2);

        jTextField1.setPreferredSize(new java.awt.Dimension(200, 23));
        searchPane.add(jTextField1);

        body.add(searchPane);

        controlsPane.setBackground(new java.awt.Color(255, 255, 204));
        controlsPane.setMaximumSize(new java.awt.Dimension(32767, 44));
        controlsPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jButton1.setText("Buscar");
        controlsPane.add(jButton1);

        body.add(controlsPane);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Apellidos", "Telefono", "Estado Civil", "Direccion", "RFC"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        body.add(jScrollPane1);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel controlsPane;
    private javax.swing.JPanel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel searchPane;
    // End of variables declaration//GEN-END:variables
}
