/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author alejandrovelasco
 */
public class ConsultaPerfilScreen extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaPerfilScreen
     */
    public ConsultaPerfilScreen() {
        initComponents();
         try{
            btnBuscar.setIcon(setIcon("/imagenes/search1.png",btnBuscar));
        }catch(Exception e){
            System.err.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        searchPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        controlsPane = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        controlsPane1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Consulta de Perfil");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 204, 255));
        body.setLayout(new javax.swing.BoxLayout(body, javax.swing.BoxLayout.PAGE_AXIS));

        searchPane.setBackground(new java.awt.Color(255, 204, 255));
        searchPane.setMaximumSize(new java.awt.Dimension(32767, 35));

        jLabel2.setText("Buscar ID");
        searchPane.add(jLabel2);

        jTextField1.setPreferredSize(new java.awt.Dimension(200, 23));
        searchPane.add(jTextField1);

        body.add(searchPane);

        controlsPane.setBackground(new java.awt.Color(255, 204, 255));
        controlsPane.setMaximumSize(new java.awt.Dimension(32767, 35));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        controlsPane.add(btnBuscar);

        body.add(controlsPane);

        controlsPane1.setBackground(new java.awt.Color(255, 204, 255));
        controlsPane1.setMaximumSize(new java.awt.Dimension(32767, 35));
        body.add(controlsPane1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Ultimo grado", "Cedula", "Experiencia", "Expediente Clinico", "Expediente COVID", "Proyectos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        body.add(jScrollPane1);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    public Icon setIcon(String url, JButton menu){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = 24;
        int alto = 24;
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel controlsPane;
    private javax.swing.JPanel controlsPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel searchPane;
    // End of variables declaration//GEN-END:variables
}
