/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import Model.Conexion;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.sqlite.SQLiteException;

/**
 *
 * @author alejandrovelasco
 */
public class ConsultaDocenteScreen extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaDocente
     */
    public ConsultaDocenteScreen() {
        initComponents();

        try {
            btnBuscar.setIcon(setIcon("/imagenes/search1.png", btnBuscar));
            btnDelete.setIcon(setIcon("/imagenes/delete.png", btnDelete));
        } catch (Exception e) {
            System.err.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        searchPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        controlsPane = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbSucces = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbRFC = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbEstadoCiv = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(255, 255, 102));
        head.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Consulta de Docente");
        head.add(jLabel1);

        add(head, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 204));
        body.setLayout(new javax.swing.BoxLayout(body, javax.swing.BoxLayout.PAGE_AXIS));

        searchPane.setBackground(new java.awt.Color(255, 255, 204));
        searchPane.setMaximumSize(new java.awt.Dimension(32767, 44));
        searchPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel2.setText("Numero de Empleado");
        searchPane.add(jLabel2);

        txtSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        searchPane.add(txtSearch);

        body.add(searchPane);

        controlsPane.setBackground(new java.awt.Color(255, 255, 204));
        controlsPane.setMaximumSize(new java.awt.Dimension(32767, 44));
        controlsPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        controlsPane.add(btnBuscar);

        btnDelete.setText("Borrar busqueda");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        controlsPane.add(btnDelete);

        body.add(controlsPane);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setBackground(new java.awt.Color(255, 255, 153));

        lbSucces.setBackground(new java.awt.Color(0, 255, 0));
        lbSucces.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jPanel7.add(lbSucces);

        jPanel1.add(jPanel7);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3);
        jPanel2.add(lbNombre);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Apellidos:");
        jPanel3.add(jLabel5);
        jPanel3.add(lbApellidos);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setText("RFC:");
        jPanel4.add(jLabel7);
        jPanel4.add(lbRFC);

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setText("Estado civil:");
        jPanel5.add(jLabel9);
        jPanel5.add(lbEstadoCiv);

        jPanel1.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel11.setText("Telefono:");
        jPanel6.add(jLabel11);
        jPanel6.add(lbTelefono);

        jPanel1.add(jPanel6);

        body.add(jPanel1);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String sentence = "", id = "",consult,stateRegister;

        id = txtSearch.getText();
        
        if (txtSearch.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo vacio", "Hey!!", JOptionPane.WARNING_MESSAGE);
            } 
        try {
                    Conexion cc = new Conexion();
        Connection cn = cc.conectar();
            
            Statement nst = cn.createStatement();
            consult = "SELECT * FROM docente WHERE id=" + id;
            ResultSet data = nst.executeQuery(consult);
            stateRegister = data.getString("estado");       
            
            if(stateRegister.equals("inactivo")){
                JOptionPane.showMessageDialog(null, "El registro  esta inactivo",
                        "Hey!", JOptionPane.WARNING_MESSAGE);
               
            }else{
                Statement st = cn.createStatement();
         
                sentence = "SELECT * FROM docente where id==" + id;
                ResultSet datos = st.executeQuery(sentence);
                
                lbSucces.setText("Registro encontrado");
                //insert labels
                lbNombre.setText(datos.getString("nombre"));
                lbApellidos.setText(datos.getString("apellidos"));
                lbRFC.setText(datos.getString("rfc"));
                lbEstadoCiv.setText(datos.getString("estado_civil"));
                lbTelefono.setText(datos.getString("telefono"));
                
                txtSearch.setText("");
            }

        } catch (SQLiteException e) {
            System.out.println(e.getMessage());
        } catch (SQLException ex) {
            //Logger.getLogger(ConsultaDocenteScreen.class.getName()).log(Level.SEVERE, null, ex);
             System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Registro No encontrado", "Hey!!", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(ConsultaDocenteScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        lbSucces.setText("");
        lbNombre.setText("");
                lbApellidos.setText("");
                lbRFC.setText("");
                lbEstadoCiv.setText("");
                lbTelefono.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    public Icon setIcon(String url, JButton menu) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = 24;
        int alto = 24;

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel controlsPane;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbEstadoCiv;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbRFC;
    private javax.swing.JLabel lbSucces;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JPanel searchPane;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
