
import Screens.AltaDocenteScreen;
import Screens.InicioScreen;
import Screens.AltaDatosProfecionalesScreen;
import Screens.ConsultaDocenteScreen;
import Screens.ConsultaPerfilScreen;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;

/**
 *
 * @author alejandrovelasco
 */
public class MainForm extends javax.swing.JFrame {
    
    InicioScreen inicioScreen = new InicioScreen();
    AltaDocenteScreen altaDocenteScreen = new AltaDocenteScreen();
    AltaDatosProfecionalesScreen altaDatosProfecionalesScreen = new AltaDatosProfecionalesScreen();
    ConsultaDocenteScreen consultaDocenteScreen = new ConsultaDocenteScreen();
    ConsultaPerfilScreen consultaPerfilScreen = new ConsultaPerfilScreen();
    
    public MainForm() {
        initComponents();
        
        //Init visible Screens
        container.add(inicioScreen);
        inicioScreen.setVisible(true);
        altaDocenteScreen.setVisible(false);
        altaDatosProfecionalesScreen.setVisible(false);
        consultaDocenteScreen.setVisible(false);
        consultaPerfilScreen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicio = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        altaDocentes = new javax.swing.JMenuItem();
        altaDatosProfecionales = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        consultaDocenteMenu = new javax.swing.JMenuItem();
        ConsultaPerfilMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));

        container.setLayout(new java.awt.BorderLayout());
        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(75, 44));
        jMenuBar1.setSize(new java.awt.Dimension(75, 44));

        inicio.setText("Inicio");
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(inicio);
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Datos Personales");

        altaDocentes.setText("Alta de Docente");
        altaDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaDocentesActionPerformed(evt);
            }
        });
        jMenu3.add(altaDocentes);

        altaDatosProfecionales.setText("Alta de Datos Profecionales");
        altaDatosProfecionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaDatosProfecionalesActionPerformed(evt);
            }
        });
        jMenu3.add(altaDatosProfecionales);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        consultaDocenteMenu.setText("Consulta Docente");
        consultaDocenteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDocenteMenuActionPerformed(evt);
            }
        });
        jMenu4.add(consultaDocenteMenu);

        ConsultaPerfilMenu.setText("Consuta Perfil");
        ConsultaPerfilMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPerfilMenuActionPerformed(evt);
            }
        });
        jMenu4.add(ConsultaPerfilMenu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaDocenteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDocenteMenuActionPerformed
       if(consultaDocenteScreen.isVisible()){
           
       }else{
           inicioScreen.setVisible(false);
           altaDatosProfecionalesScreen.setVisible(false);
           altaDocenteScreen.setVisible(false);
           consultaPerfilScreen.setVisible(false);
           
           container.add(consultaDocenteScreen);
           consultaDocenteScreen.setVisible(true);
       }
    }//GEN-LAST:event_consultaDocenteMenuActionPerformed

    private void ConsultaPerfilMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPerfilMenuActionPerformed
        if(consultaPerfilScreen.isVisible()){
            
        }else{
            inicioScreen.setVisible(false);
            altaDatosProfecionalesScreen.setVisible(false);
            altaDocenteScreen.setVisible(false);
            consultaDocenteScreen.setVisible(false);
            
            container.add(consultaPerfilScreen);
            
            consultaPerfilScreen.setVisible(true);
            
            
        }
    }//GEN-LAST:event_ConsultaPerfilMenuActionPerformed

    private void altaDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaDocentesActionPerformed
        if(altaDocenteScreen.isVisible()){
            System.out.println("Estas en la ventana");
        }else{
            inicioScreen.setVisible(false);
            altaDatosProfecionalesScreen.setVisible(false);
            consultaPerfilScreen.setVisible(false);
            consultaDocenteScreen.setVisible(false);
            
            container.add(altaDocenteScreen);
            altaDocenteScreen.setVisible(true);
            
        }
    }//GEN-LAST:event_altaDocentesActionPerformed

    private void inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseClicked
        if(inicioScreen.isVisible()){
            
        }else{
            altaDatosProfecionalesScreen.setVisible(false);
            altaDatosProfecionalesScreen.setVisible(false);
            consultaPerfilScreen.setVisible(false);
            consultaDocenteScreen.setVisible(false);
            
            inicioScreen.setVisible(true);
        }
    }//GEN-LAST:event_inicioMouseClicked

    private void altaDatosProfecionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaDatosProfecionalesActionPerformed
        if(altaDatosProfecionalesScreen.isVisible()){
            
        }else{
            inicioScreen.setVisible(false);
            altaDocenteScreen.setVisible(false);
            consultaPerfilScreen.setVisible(false);
            consultaDocenteScreen.setVisible(false);
            
            container.add(altaDatosProfecionalesScreen);            
            altaDatosProfecionalesScreen.setVisible(true);
          
            
        }
    }//GEN-LAST:event_altaDatosProfecionalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        try {
                    //DB conexion
            Conexion cc = new Conexion();
             Connection cn = cc.conectar();
            PreparedStatement ps = cn.prepareStatement("INSERT INTO docente VALUES(?,?,?,?,?,?,?);");
            
            ps.setInt(1, 11);
            ps.setString(2, "Fernando");
            ps.setString(3, "Torres");
            ps.setString(4, "002021jk");
            ps.setString(5, "Casado");
            ps.setString(6, "Guadalajara");
            ps.setString(7, "3341643969");
            
            ps.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsultaPerfilMenu;
    private javax.swing.JMenuItem altaDatosProfecionales;
    private javax.swing.JMenuItem altaDocentes;
    private javax.swing.JMenuItem consultaDocenteMenu;
    private javax.swing.JPanel container;
    private javax.swing.JMenu inicio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
