
import Model.Conexion;
import Screens.AltaDocenteScreen;
import Screens.InicioScreen;
import Screens.AltaDatosProfecionalesScreen;
import Screens.ConsultaDocenteScreen;
import Screens.ConsultaPerfilScreen;
import Screens.AltaAlumnosScreen;
import java.awt.Image;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author alejandrovelasco
 */
public class MainForm extends javax.swing.JFrame {

    InicioScreen inicioScreen = new InicioScreen();
    AltaDocenteScreen altaDocenteScreen = new AltaDocenteScreen();
    AltaDatosProfecionalesScreen altaDatosProfecionalesScreen = new AltaDatosProfecionalesScreen();
    ConsultaDocenteScreen consultaDocenteScreen = new ConsultaDocenteScreen();
    ConsultaPerfilScreen consultaPerfilScreen = new ConsultaPerfilScreen();
    AltaAlumnosScreen altaAlumnos = new AltaAlumnosScreen();

    public MainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            inicioM.setIcon(setIcon("/imagenes/Home.png", inicioM));
            consultM.setIcon(setIcon("/imagenes/search.png", consultM));
            datosM.setIcon(setIcon("/imagenes/teamwork.png", datosM));

            altaDocentes.setIcon(setIconItem("/imagenes/registro.png", altaDocentes));
            altaDatosProfecionales.setIcon(setIconItem("/imagenes/dataUpdate.png", altaDatosProfecionales));
            
            consultaDocenteMenu.setIcon(setIconItem("/imagenes/look.png", consultaDocenteMenu));
            ConsultaPerfilMenu.setIcon(setIconItem("/imagenes/look2.png", consultaDocenteMenu));
            
            mAlumnos.setIcon(setIcon("/imagenes/alumno.png", mAlumnos));
            altaAlumnosMOption.setIcon(setIconItem("/imagenes/login.png", altaAlumnosMOption));
            
        } catch (Exception e) {
            System.err.println(e);
        }

        //Init visible Screens
        container.add(inicioScreen);
        inicioScreen.setVisible(true);
        altaDocenteScreen.setVisible(false);
        altaDatosProfecionalesScreen.setVisible(false);
        consultaDocenteScreen.setVisible(false);
        consultaPerfilScreen.setVisible(false);
        altaAlumnos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicioM = new javax.swing.JMenu();
        datosM = new javax.swing.JMenu();
        altaDocentes = new javax.swing.JMenuItem();
        altaDatosProfecionales = new javax.swing.JMenuItem();
        consultM = new javax.swing.JMenu();
        consultaDocenteMenu = new javax.swing.JMenuItem();
        ConsultaPerfilMenu = new javax.swing.JMenuItem();
        mAlumnos = new javax.swing.JMenu();
        altaAlumnosMOption = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        container.setLayout(new java.awt.BorderLayout());
        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(75, 44));
        jMenuBar1.setSize(new java.awt.Dimension(75, 44));

        inicioM.setText("Inicio");
        inicioM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMMouseClicked(evt);
            }
        });
        jMenuBar1.add(inicioM);

        datosM.setText("Datos Personales");

        altaDocentes.setText("Alta de Docente");
        altaDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaDocentesActionPerformed(evt);
            }
        });
        datosM.add(altaDocentes);

        altaDatosProfecionales.setText("Alta de Datos Profecionales");
        altaDatosProfecionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaDatosProfecionalesActionPerformed(evt);
            }
        });
        datosM.add(altaDatosProfecionales);

        jMenuBar1.add(datosM);

        consultM.setText("Consultas");

        consultaDocenteMenu.setText("Consulta Docente");
        consultaDocenteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDocenteMenuActionPerformed(evt);
            }
        });
        consultM.add(consultaDocenteMenu);

        ConsultaPerfilMenu.setText("Consuta Perfil");
        ConsultaPerfilMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPerfilMenuActionPerformed(evt);
            }
        });
        consultM.add(ConsultaPerfilMenu);

        jMenuBar1.add(consultM);

        mAlumnos.setText("Alumnos");

        altaAlumnosMOption.setText("Alta de Alumnos");
        altaAlumnosMOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaAlumnosMOptionActionPerformed(evt);
            }
        });
        mAlumnos.add(altaAlumnosMOption);

        jMenuBar1.add(mAlumnos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaDocenteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDocenteMenuActionPerformed
        if (consultaDocenteScreen.isVisible()) {

        } else {
            inicioScreen.setVisible(false);
            altaDatosProfecionalesScreen.setVisible(false);
            altaDocenteScreen.setVisible(false);
            consultaPerfilScreen.setVisible(false);
            altaAlumnos.setVisible(false);

            container.add(consultaDocenteScreen);
            consultaDocenteScreen.setVisible(true);
        }
    }//GEN-LAST:event_consultaDocenteMenuActionPerformed

    private void ConsultaPerfilMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPerfilMenuActionPerformed
        if (consultaPerfilScreen.isVisible()) {

        } else {
            inicioScreen.setVisible(false);
            altaDatosProfecionalesScreen.setVisible(false);
            altaDocenteScreen.setVisible(false);
            consultaDocenteScreen.setVisible(false);
            altaAlumnos.setVisible(false);

            container.add(consultaPerfilScreen);

            consultaPerfilScreen.setVisible(true);

        }
    }//GEN-LAST:event_ConsultaPerfilMenuActionPerformed

    private void altaDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaDocentesActionPerformed
        if (altaDocenteScreen.isVisible()) {
            System.out.println("Estas en la ventana");
        } else {
            inicioScreen.setVisible(false);
            altaDatosProfecionalesScreen.setVisible(false);
            consultaPerfilScreen.setVisible(false);
            consultaDocenteScreen.setVisible(false);
            altaAlumnos.setVisible(false);

            container.add(altaDocenteScreen);
            altaDocenteScreen.setVisible(true);

        }
    }//GEN-LAST:event_altaDocentesActionPerformed

    private void inicioMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMMouseClicked
        if (inicioScreen.isVisible()) {

        } else {

            altaDocenteScreen.setVisible(false);
            altaDatosProfecionalesScreen.setVisible(false);
            consultaPerfilScreen.setVisible(false);
            consultaDocenteScreen.setVisible(false);
            altaAlumnos.setVisible(false);

            container.add(inicioScreen);
            inicioScreen.setVisible(true);
        }
    }//GEN-LAST:event_inicioMMouseClicked

    private void altaDatosProfecionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaDatosProfecionalesActionPerformed
        if (altaDatosProfecionalesScreen.isVisible()) {

        } else {
            inicioScreen.setVisible(false);
            altaDocenteScreen.setVisible(false);
            consultaPerfilScreen.setVisible(false);
            consultaDocenteScreen.setVisible(false);
            altaAlumnos.setVisible(false);

            container.add(altaDatosProfecionalesScreen);
            altaDatosProfecionalesScreen.setVisible(true);

        }
    }//GEN-LAST:event_altaDatosProfecionalesActionPerformed

    private void altaAlumnosMOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaAlumnosMOptionActionPerformed
       if (altaAlumnos.isVisible()) {

        } else {
            inicioScreen.setVisible(false);
            altaDocenteScreen.setVisible(false);
            consultaPerfilScreen.setVisible(false);
            consultaDocenteScreen.setVisible(false);
            altaDatosProfecionalesScreen.setVisible(false);

            container.add(altaAlumnos);
            altaAlumnos.setVisible(true);
        }
    }//GEN-LAST:event_altaAlumnosMOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    public Icon setIcon(String url, JMenu menu) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = 24;
        int alto = 24;

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;
    }

    public Icon setIconItem(String url, JMenuItem menu) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = 24;
        int alto = 24;

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsultaPerfilMenu;
    private javax.swing.JMenuItem altaAlumnosMOption;
    private javax.swing.JMenuItem altaDatosProfecionales;
    private javax.swing.JMenuItem altaDocentes;
    private javax.swing.JMenu consultM;
    private javax.swing.JMenuItem consultaDocenteMenu;
    private javax.swing.JPanel container;
    private javax.swing.JMenu datosM;
    private javax.swing.JMenu inicioM;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mAlumnos;
    // End of variables declaration//GEN-END:variables
}
